# Generated by Django 3.1.5 on 2021-01-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('rollno', models.CharField(max_length=240, verbose_name='RollNo')),
                ('maths', models.CharField(max_length=20)),
                ('phys', models.CharField(max_length=20)),
                ('chem', models.CharField(max_length=20)),
                ('total', models.CharField(max_length=20)),
                ('perc', models.CharField(max_length=20)),
            ],
        ),
    ]
